### ISSUE TITLE
FAQs

### ISSUE THREAD

**Issue by orchid00** [au-research/your-first-step-to-fair#1]
URL https://au-research.github.io/your-first-step-to-fair/faqs
currently leads to nothing.
Wither remove the link from the top menu or add text to the page

**Comment by mpfl** [comment]
Ah - this is a carry over from the FAIR101 template.

Probably remove it - I'm fundamentally opposed to the idea of "FAQs" on website anyway.

**Comment by mpfl** [comment]
Fixed with commit #aaf8818
