### ISSUE TITLE
Reconsider breadcrumbs

### ISSUE THREAD

**Issue by ragamouf** [au-research/your-first-step-to-fair#2]
I like the plain look and feel, but the breadcrumb navigation at the top and bottom interrupt the clarity. Are we in danger of reinventing the wheel here?

Why not consider a template similar to: [UBC's Intro to Jekyll tutorial](https://ubc-library-rc.github.io/intro-jekyll/)? It's much more in line with conventions like the [carpentries curriculum development handbook](https://cdh.carpentries.org/) and [gitbook tutorials](https://petebankhead.gitbooks.io/imagej-intro/content/).

**Comment by mpfl** [comment]
This issue should be raised on [the training template repo](https://github.com/au-research/training-template).
