### ISSUE TITLE
ep 3 where is the dataset from?

### ISSUE THREAD

**Issue by orchid00** [au-research/your-first-step-to-fair#3]
https://au-research.github.io/your-first-step-to-fair/3-well-structured-data

Where is the data coming from? I think best practice will be to link to a metadata record of it. 
Can you add that to somewhere it shows its metadata?
If this metadata doesn't exist. I recommend this to be places in a data folder within this repo and and a README file with some metadata that is at least human readable, and it includes a license for reuse, otherwise technically people can not reuse this.

**Comment by mpfl** [comment]
The data comes from my solar panels at home :-D

I have deliberately _not_ created a metadata record for it as the lack of metadata is intended to teach the learners.

The dataset is a part of the lesson materials, which are all licenced CC BY 4.0.

**Comment by orchid00** [comment]
@mpfl would you add a little description about the dataset?
