### ISSUE TITLE
Ep 4 add activity

### ISSUE THREAD

**Issue by orchid00** [au-research/your-first-step-to-fair#4]
https://au-research.github.io/your-first-step-to-fair/4-open-data-format

Can you add an activity / Question
what do you think are the limitations of using a closed or proprietary format (such as .jpg, docx, PDF, etc)?

**Comment by mpfl** [comment]
Activity added to episode 4 in commit [b8523ab](https://github.com/au-research/your-first-step-to-fair/commit/b8523abb801f283afbf52705a4852272542d1f4d)
