### ISSUE TITLE
Ep 5 suggestion

### ISSUE THREAD

**Issue by orchid00** [au-research/your-first-step-to-fair#5]
https://au-research.github.io/your-first-step-to-fair/5-select-a-data-repository

can we add this 
https://journals.plos.org/plosbiology/s/recommended-repositories
next to the nature recommended ones

**Comment by mpfl** [comment]
Good idea.

Added in commit [3a0672c](https://github.com/au-research/your-first-step-to-fair/commit/3a0672c8d5b903e51013830c572adf36f8273298)
