### ISSUE TITLE
Ep 6 to consider

### ISSUE THREAD

**Issue by orchid00** [au-research/your-first-step-to-fair#6]
https://au-research.github.io/your-first-step-to-fair/6-write-metadata

To consider.
Maybe we can add here the checklist for training materials for people to think about other metadata that might be relevant to save.

maybe also worth mentioning why zenodo is the example. Because of its commitment to FAIR https://about.zenodo.org/principles/

**Comment by mpfl** [comment]
Added link to Zenodo's FAIR commitment to ep 5 in commit [3a0672c](https://github.com/au-research/your-first-step-to-fair/commit/3a0672c8d5b903e51013830c572adf36f8273298)

**Comment by orchid00** [comment]
Thanks @mpfl I will close this issue I rethought about the metadata and discarded that suggestion
