### ISSUE TITLE
Suggestions for improvements

### ISSUE THREAD

**Issue by kgrussell** [au-research/your-first-step-to-fair#7]
Introduction: 
link to ARDC FAIR page rather than Go-FAIR one
https://ardc.edu.au/resources/working-with-data/fair-data/

replace: "that not all data should be made open", by "that not all data can be made open, "

replace "free-to-download,"  with "free to download or access"

 Add a sentence after "certain characteristics."  "This will enable optimal reuse of the data by for both humans and machines."

**Comment by mpfl** [comment]
Suggestions incorporated in commit [037f901](https://github.com/au-research/your-first-step-to-fair/commit/037f901c43b30a40a37ef2b42cecc2e972f03219).
